### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by Oshirowanen** [dcousens/fast-dat-parser#31]
Got this successfully compiled and running.  I tried the command:

cat ~/.bitcoin/blocks/blk02272.dat | ./parser -t1 | ./bestchain > chain.dat

Which is the latest blk*.dat file as of writing the issue request.

It creates a chain.dat file.  How do I read the chain.dat file, or how do I use the chain.dat file?

**Comment by junderw** [comment]
That is out of scope for this project.

It is merely made to order the data contained within dat files (since bitcoind doesn't order them in any way)...

Any parsing to human readable data requires knowledge of what a dat file contains and how to use certain tools to parse it.

Some other users have asked advice in previous issues. Please use the search function.

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/issues/1562

Here, I found it for you.
